version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd blog_nextjs_frontend && npm run dev"
    ports:
      - "3000:3000"
